#!/usr/bin/env python3
"""Table 3 of the paper (``tab:Autopsy``): both autopsies on one page.

The table was hand-written when the two autopsies were first run, and drifted:
its portfolio block still carried the numbers from a 12-replication pilot after
the 50-replication run had replaced them everywhere else.  This script generates
it instead, from the same two modules that generate the figure and the portfolio
table, so the three can no longer disagree.

    shortest path   shortest_path_autopsy.load_medians / .correct / .ETA
                    reported at ebar = 0.5, corrected, and their own ebar = 0
                    control, all medians across their replications
    portfolio       portfolio_autopsy.eta_table (the cached premium) and
                    .reported_medians, at tau = 2

Writes ``outputs/tab_autopsy.tex``.  ``--check`` compares against the values
currently printed in the paper and reports the drift without writing anything.
"""

import argparse
import os

import portfolio_autopsy as pf
import shortest_path_autopsy as sp

OUTDIR = sp.OUTDIR
OUT = os.path.join(OUTDIR, "tab_autopsy.tex")

SP_METHODS = [("SPOplus", r"\textsc{spo+}"), ("LS", "least squares")]
PF_METHODS = [("SPOplus", r"\textsc{spo+}"), ("LS", "least squares")]
PF_TAU = 2

# What 12_implementation.tex prints today, for --check.
IN_PAPER = {
    "sp_eta": {1: 15.47, 2: 10.45, 4: 6.73, 6: 5.50, 8: 4.93},
    "pf_eta": {1: 6.13, 4: 7.74, 8: 5.28, 16: 2.38},
    "pf_SPOplus_rep": {1: 6.18, 4: 7.67, 8: 5.23, 16: 2.73},
    "pf_SPOplus_corr": {1: 0.06, 4: -0.08, 8: -0.05, 16: 0.36},
    "pf_LS_rep": {1: 6.17, 4: 7.68, 8: 5.35, 16: 3.50},
    "pf_LS_corr": {1: 0.04, 4: -0.07, 8: 0.08, 16: 1.15},
    "pf_Baseline_corr": {1: 19.76, 4: 14.31, 8: 19.32, 16: 27.12},
}


def shortest_path():
    """{'eta': {deg: %}, method: {'rep'|'corr'|'ctl': {deg: %}}}, all percent."""
    rep = sp.load_medians(sp.EBAR)
    ctl = sp.load_medians(0.0)
    out = {"eta": dict(sp.ETA)}
    for key, _ in SP_METHODS:
        out[key] = {
            "rep": {d: rep[key][d] for d in sp.DEGREES},
            "corr": {d: sp.correct(rep[key][d], sp.ETA[d]) for d in sp.DEGREES},
            "ctl": {d: ctl[key][d] for d in sp.DEGREES},
        }
    return out


def portfolio(tau=PF_TAU):
    """Same shape, at one tau, in percent.  Reads the cached premium."""
    cache = pf.read_cache()
    if len(cache) == 0:
        raise SystemExit("data/cache/portfolio_eta.csv is empty; run portfolio_autopsy.py first")
    eta = pf.eta_table(cache)
    med = pf.reported_medians()
    out = {"eta": {d: 100 * eta[(tau, d)][0] for d in pf.DEGREES},
           "se": {d: 100 * eta[(tau, d)][1] for d in pf.DEGREES},
           "reps": max(v[2] for v in eta.values()),
           "n_test": int(cache["n_test"].max())}
    for key in [k for k, _ in PF_METHODS] + ["Baseline"]:
        e = {d: eta[(tau, d)][0] for d in pf.DEGREES}
        out[key] = {
            "rep": {d: 100 * med[(tau, d)][key] for d in pf.DEGREES},
            "corr": {d: 100 * pf.correct(med[(tau, d)][key], e[d]) for d in pf.DEGREES},
        }
    return out


def _n(x):
    """LaTeX-safe two-decimal number: a minus sign is math, not a hyphen."""
    s = f"{x:.2f}"
    return f"${s}$" if s.startswith("-") else s


def build(path=OUT):
    s, p = shortest_path(), portfolio()
    sd, pd_ = sp.DEGREES, pf.DEGREES
    def rowvals(dct, degs):
        return " & ".join(_n(dct[d]) for d in degs)

    lines = [
        "% !TEX root = ../00_main.tex",
        "% GENERATED by code/make_autopsy_table.py.  Do not hand-edit.",
        f"% portfolio block: {p['reps']} replications x {p['n_test']} test points, tau = {PF_TAU}.",
        "\\begin{table}[t]", "\\centering",
        "\\caption{\\textbf{Both autopsies.} Reported \\(\\NRegLA\\) and the corresponding",
        "\\(\\NRegTM\\), with the normalized premium \\(\\eta\\) that separates them.  For the",
        "shortest path, the third line of each block is Elmachtoub and Grigas's own noiseless",
        "control, where the two oracles coincide; the corrected values reproduce it although",
        "the control never enters the correction.  All figures are percentages.}",
        "\\label{tab:Autopsy}", "\\small",
        "\\begin{tabular}{llrrrrr}", "\\toprule",
        "& & \\multicolumn{5}{c}{polynomial degree} \\\\",
        "\\cmidrule(lr){3-7}",
        "\\multicolumn{2}{l}{\\textbf{Shortest path}, \\(n = 5000\\), \\(\\bar\\varepsilon = 0.5\\)}",
        f"  & {' & '.join(str(d) for d in sd)} \\\\",
        "\\midrule",
        f"\\multicolumn{{2}}{{l}}{{premium \\(\\eta\\)}} & {rowvals(s['eta'], sd)} \\\\",
    ]
    for key, lab in SP_METHODS:
        lines += ["\\addlinespace",
                  f"{lab}   & reported  & {rowvals(s[key]['rep'], sd)} \\\\",
                  f"        & corrected & {rowvals(s[key]['corr'], sd)} \\\\",
                  f"        & their \\(\\bar\\varepsilon = 0\\) & {rowvals(s[key]['ctl'], sd)} \\\\"]
    lines += [
        "\\midrule",
        "& & \\multicolumn{4}{c}{polynomial degree} \\\\",
        "\\cmidrule(lr){3-6}",
        f"\\multicolumn{{2}}{{l}}{{\\textbf{{Portfolio}}, \\(n = 1000\\), \\(\\tau = {PF_TAU}\\)}}",
        f"  & {' & '.join(str(d) for d in pd_)} & \\\\",
        "\\midrule",
        f"\\multicolumn{{2}}{{l}}{{premium \\(\\eta\\)}} & {rowvals(p['eta'], pd_)} & \\\\",
    ]
    for key, lab in PF_METHODS:
        lines += ["\\addlinespace",
                  f"{lab}   & reported  & {rowvals(p[key]['rep'], pd_)} & \\\\",
                  f"        & corrected & {rowvals(p[key]['corr'], pd_)} & \\\\"]
    lines += ["\\addlinespace",
              f"non-contextual & corrected & {rowvals(p['Baseline']['corr'], pd_)} & \\\\",
              "\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w").write("\n".join(lines))
    print("wrote", os.path.normpath(path))


def check(tol=0.02):
    s, p = shortest_path(), portfolio()
    got = {"sp_eta": s["eta"], "pf_eta": p["eta"]}
    for key, _ in PF_METHODS:
        got[f"pf_{key}_rep"] = p[key]["rep"]
        got[f"pf_{key}_corr"] = p[key]["corr"]
    got["pf_Baseline_corr"] = p["Baseline"]["corr"]

    drift = 0
    print(f"{'quantity':<22}{'deg':>5}{'computed':>11}{'in paper':>11}{'delta':>9}")
    for name, published in IN_PAPER.items():
        for d, was in published.items():
            now = got[name][d]
            if abs(now - was) > tol:
                drift += 1
                print(f"{name:<22}{d:>5}{now:>11.2f}{was:>11.2f}{now - was:>+9.2f}")
    print(f"\n  {drift} entries differ from the paper by more than {tol:.2f} points."
          if drift else f"\n  every entry matches the paper to {tol:.2f} points.")
    return drift


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="compare against the numbers printed in the paper; write nothing")
    a = ap.parse_args()
    if a.check:
        check()
    else:
        build()


if __name__ == "__main__":
    main()
